"""Add symbol column to portfolio

Revision ID: d61e89a23bdc
Revises: aa742c3a4d45
Create Date: 2025-07-03 20:50:31.867570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61e89a23bdc'
down_revision: Union[str, Sequence[str], None] = 'aa742c3a4d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('symbol', sa.String(), nullable=False, server_default='UNKNOWN'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'symbol')
    # ### end Alembic commands ###
